<img src="https://www.mines.edu/webcentral/wp-content/uploads/sites/267/2019/02/horizontallightbackground.jpg" width="100%"> 
### CSCI250 Python Computing: Building a Sensor System
<hr style="height:5px" width="100%" align="left">

# `numpy`: 2D arrays

# Objectives
* introduce 2D `numpy` arrays and operations
* discuss `numpy` array 
    * attributes
    * reshaping
    * slicing & striding

# Resources
* [numpy.org](http://www.numpy.org)
* [`numpy` user guide](https://docs.scipy.org/doc/numpy/user)
* [`numpy` reference](https://docs.scipy.org/doc/numpy/reference)

# `import`
`numpy` comes with methods optimized for array operations. 

Can be accessed by typing a variable name, followed by `.` and **TAB**. 

The name of the method followed by `?` returns the selfdoc. 

In [1]:
import numpy as np

# array creation
There are multiple mechanisms to define 2D `numpy` arrays.

## `np.array()`
Create a `numpy` array from a Python list of lists.

In [2]:
x = np.array( [ [2,3,4,5], [3,4,5,6], [4,5,6,7] ], dtype=float)
print(x)
type(x)

[[2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]


numpy.ndarray

## `np.empty()`
Form an array of given shape and type, without initializing entries.

In [3]:
nRows = 3 # number of rows
nCols = 4 # number of columns

a = np.empty( [nRows,nCols] )
print(a)

[[2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]


## `np.zeros()`
Returns a new array of given shape and type, filled with zeros.

In [4]:
zI = np.zeros( [nRows,nCols], dtype=int)
zF = np.zeros( [nRows,nCols], dtype=float)
zB = np.zeros( [nRows,nCols], dtype=bool)
zC = np.zeros( [nRows,nCols], dtype=complex)

In [5]:
print(zI)
print(zF)
print(zB)
print(zC)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


## `np.ones()`
Returns a new array of given shape and type, filled with ones.

In [6]:
oI = np.ones( [nRows,nCols], dtype=int)
oF = np.ones( [nRows,nCols], dtype=float)
oB = np.ones( [nRows,nCols], dtype=bool)
oC = np.ones( [nRows,nCols], dtype=complex)

In [7]:
print(oI)
print(oF)
print(oB)
print(oC)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]


# array indexing

Access `numpy` array elements with a list of indexes (start with `0`).

`ndarray` type is **mutable**.

In [8]:
a = np.ones( [nRows,nCols], dtype=int)
print(a)
print( id(a) )

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
1719940537776


We can use negative indexes - count from the start of the array.

In [9]:
print(a)

a[+2,+2] = -9
print(a)
print( id(a) )

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ 1  1  1  1]
 [ 1  1  1  1]
 [ 1  1 -9  1]]
1719940537776


We can use negative indexes - count from the end of the array.

In [10]:
print(a)

a[-2,-2] = +9
print(a)
print( id(a) )

[[ 1  1  1  1]
 [ 1  1  1  1]
 [ 1  1 -9  1]]
[[ 1  1  1  1]
 [ 1  1  9  1]
 [ 1  1 -9  1]]
1719940537776


# array slicing

We can access/modify a range of elements in an 2D `numpy` array.

In [11]:
a = np.ones( [nRows,nCols] , dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
a[ 1:3, 1:3 ] = 0
print(a)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]]


# array attributes
Reflect information that is intrinsic to the array.  

<img src="http://www.dropbox.com/s/fcucolyuzdjl80k/todo.jpg?raw=1" width="10%" align="right">

Explain the **attributes** associated with 2D `ndarray`.
* Add comments explaining their purpose. 
* Include examples demonstrating their usage.

In [13]:
o = np.ones( [nRows,nCols] )
#makes new array of ones with dimensions nRows, nCols

In [14]:
o.ndim
#returns number of dimensions

2

In [15]:
o.shape
#returns size of each dimension, in this case number of rows and columns

(3, 4)

In [16]:
o.size
#returns total number of elements

12

In [17]:
o.dtype
#returns dtype of array elements

dtype('float64')

In [18]:
o.nbytes
#returns number of bytes in array

96

In [19]:
o.itemsize
#returns number of bytes in each array element (recall: 8 bits ber byte)

8

# array methods
Array methods facilitate efficient operations on `numpy` arrays. 

2D `numpy` arrays 
* inherit the methods discussed for 1D `numpy` arrays
* add methods tuned for multidimensional arrays.

<img src="http://www.dropbox.com/s/fcucolyuzdjl80k/todo.jpg?raw=1" width="10%" align="right">

Explain the **methods** associated with 2D `ndarray`s.
* Add comments explaining their purpose. 
* Include examples demonstrating their usage.

## array ordering
`numpy` arrays can be ordered in different ways:
* **row major**: row elements are contiguous in memory
* **column major**: column elements are contiguous in memory

## array access
`numpy` arrays are accessed efficiently by caching:
* **row major**: loop over columns first, then over rows
* **column major**: loop over rows first, then over columns

## `ndarray.reshape()`
Gives a new shape to an array without changing its data.

Specifies how the elements of the `numpy` array are organized.
* `order='C'`: column index changing fastest (**C**)
* `order='F'`: row index changing fastest (**Fortran**)

### C convention - row major ordering

In [20]:
a = np.arange( nRows*nCols, dtype=int)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
bC = a.reshape( [nRows,nCols], order='C')
print(bC)
#makes array n rows and n columns in order row major, like C language

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
cC = bC.reshape( nRows*nCols, order='C')
print(cC)
#reshape backwards

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Fortran convention - column major ordering

In [ ]:
a = np.arange( nRows*nCols, dtype=int)
print(a)

In [24]:
bF = a.reshape( [nRows,nCols], order='F')
print(bF)
#reshape as 2d array with column major ordering, like language Fortran

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [25]:
cF = bF.reshape( nRows*nCols, order='F')
print(cF)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### C convention - column index changing fastest

In [26]:
print('r c')
for iRow in range(nRows):                   # slow axis
    print('')
    for iCol in range(nCols):               # fast axis - cols
        print( iRow,iCol,'\t', bC[iRow,iCol] )
        
#loop over the array how it is stored in memory. It is stored contiguously by row and then by column.

r c

0 0 	 0
0 1 	 1
0 2 	 2
0 3 	 3

1 0 	 4
1 1 	 5
1 2 	 6
1 3 	 7

2 0 	 8
2 1 	 9
2 2 	 10
2 3 	 11


### Fortran convention - row index changing fastest

In [28]:
print('r c')
for iCol in range(nCols):                   # slow axis
    print('')
    for iRow in range(nRows):               # fast axis - rows
        print( iRow,iCol,'\t', bF[iRow,iCol] )
#looping over the array as it is stored in memory, contiguously by row and then by column

r c

0 0 	 0
1 0 	 1
2 0 	 2

0 1 	 3
1 1 	 4
2 1 	 5

0 2 	 6
1 2 	 7
2 2 	 8

0 3 	 9
1 3 	 10
2 3 	 11


# array ordering/access summary

* array access is by `ndarray[iRow,iCol]`
* `numpy` defaults to the C convention (row major) 
* fastest access is achieved using 
    * exterior loop over rows
    * interior loop over columns

In [29]:
import time
nR,nC = 1024*10,1024*10

# construct a row-major array (C convention)
a = np.ones( [nR,nC], dtype=float, order='C')
a /= (nR*nC)

print(a.shape, a.nbytes/1024/1024,'Mb')

(10240, 10240) 800.0 Mb


In [30]:
tick = time.time()
s = 0
for iR in range(nR):     # outer loop over rows  
    for iC in range(nC): # inner loop over columns (efficient) 
        s += a[iR,iC]
tock = time.time()

print( format( s,'.3f') )
print( format( (tock-tick),'.0f'),'s' )

1.000
27 s


In [31]:
tick = time.time()
s = 0
for iC in range(nC):     # outer loop over columns
    for iR in range(nR): # inner loop over rows (inefficient)
        s += a[iR,iC]
tock = time.time()
       
print( format( s,'.3f') )
print( format( (tock-tick),'.0f'),'s' )

1.000
33 s


# `ndarray.reshape()`

**N.B.**: Transformation is in-place:
* efficient use of memory, but
* can lead to confusion.

In [32]:
a = np.arange( nRows*nCols , dtype=int)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [33]:
b = a.reshape( [nRows,nCols] )
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
b[0:2,0:2] = -1
print(b)

[[-1 -1  2  3]
 [-1 -1  6  7]
 [ 8  9 10 11]]


In [35]:
print(a)

[-1 -1  2  3 -1 -1  6  7  8  9 10 11]


## `ndarray.copy()`

Makes an explicit copy of an array at another location in memory.

In [37]:
a = np.arange( nRows*nCols , dtype=int)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
b = a.reshape( [nRows,nCols] ).copy()
print(b)
#you have to invoke method copy to make a NEW array rather than assigning a new title to the original

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
b[0:2,0:2] = -1
print(b)

[[-1 -1  2  3]
 [-1 -1  6  7]
 [ 8  9 10 11]]


In [40]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## `ndarray.ravel()`
Returns a contiguous flattened array.

**N.B.**: Does not make a copy of the array.

In [41]:
a = np.arange( nRows*nCols , dtype=int).reshape( [nRows,nCols])
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
b = a.ravel()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## `ndarray.flatten()`
Returns a copy of the array collapsed into one dimension.

**N.B.**: Makes a copy of the array. 

In [43]:
a = np.arange( nRows*nCols , dtype=int).reshape( [nRows,nCols], order='C')
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
b = a.flatten()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


The ordering of elements in the array matters.

In [45]:
a = np.arange( nRows*nCols , dtype=int).reshape( [nRows,nCols], order='F')
print(a)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [46]:
b = a.flatten()
print(b)
#flatten uses row major (C convention) by default

[ 0  3  6  9  1  4  7 10  2  5  8 11]


## `ndarray.resize()`
Change the shape and size of an array in place.

In [47]:
a = np.arange( nRows*nCols , dtype=int).reshape( [nRows,nCols]).copy()
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
a.resize([3,2])
print(a)
#brutal method. Just takes the elements in order using row major

[[0 1]
 [2 3]
 [4 5]]


## `ndarray.compress()`
Returns selected slices of an array along a given axis.

In [49]:
a = np.arange( nRows*nCols , dtype=int).reshape( [nRows,nCols]).copy()
print(a,'\n')

b = a.compress( [False,True,True], axis=0 )       # select rows
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [50]:
a = np.arange( nRows*nCols , dtype=int).reshape( [nRows,nCols]).copy()
print(a,'\n')

c = a.compress( [False,True,True,False], axis=1 ) # select columns
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [51]:
a = np.arange( nRows*nCols , dtype=int).reshape( [nRows,nCols]).copy()
print(a,'\n')

d = a.compress( [0,1,1], axis=0 )     # select rows
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [52]:
a = np.arange( nRows*nCols , dtype=int).reshape( [nRows,nCols]).copy()
print(a,'\n')

c = a.compress( [0,1,1,0], axis=1 )   # select columns
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 1  2]
 [ 5  6]
 [ 9 10]]


## `ndarray.squeeze()`
Remove 1D components from the shape of an array.

In [53]:
a = np.arange( nRows*nCols , dtype=int).reshape( [2,1,int(nRows*nCols/2)] )
print(a,'\n')
print(a.shape)

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]] 

(2, 1, 6)


In [54]:
b = a.squeeze( 1 )
print(b,'\n')
print(b.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

(2, 6)


## `ndarray.swapaxes()`
Interchange two axes of an array.

In [55]:
a = np.arange( nRows*nCols , dtype=int).reshape( [2,1,int(nRows*nCols/2)])
print(a,'\n')
print(a.shape)

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]] 

(2, 1, 6)


In [56]:
b = a.swapaxes(1,2)
print(b,'\n')
print(b.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]] 

(2, 6, 1)


In [61]:
c = b.squeeze(2)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## `ndarray.transpose()`
Permute the dimensions of an array.

In [62]:
a = np.arange( nRows*nCols , dtype=int).reshape( [2,1,int(nRows*nCols/2)])
print(a,'\n')
print(a.shape)

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]] 

(2, 1, 6)


In [63]:
b = a.transpose()
print(b,'\n')
print(b.shape)

[[[ 0  6]]

 [[ 1  7]]

 [[ 2  8]]

 [[ 3  9]]

 [[ 4 10]]

 [[ 5 11]]] 

(6, 1, 2)


## `ndarray.diagonal()`
Return specified diagonals.

In [64]:
a = np.arange( nRows*nCols , dtype=int).reshape( [nRows,nCols])
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [65]:
b = a.diagonal(1)
print(b)

[ 1  6 11]


## `ndarray.trace()`
Return the sum along diagonals of the array.

In [66]:
a = np.arange( nRows*nCols , dtype=int).reshape( [nRows,nCols] )
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [67]:
print(a.trace(1))

18
